const GetInterpretationType = {
    GET_INTERPRETATION: "GET_INTERPRETATION",
    GET_INTERPRETATION_SUCCESS: "GET_INTERPRETATION_SUCCESS",
    GET_INTERPRETATION_ERROR: "GET_INTERPRETATION_ERROR",
};

export default GetInterpretationType;