const GetInterpretationInfoType = {
    GET_INTERPRETATION_INFO: "GET_INTERPRETATION_INFO",
    GET_INTERPRETATION_INFO_SUCCESS: "GET_INTERPRETATION_INFO_SUCCESS",
    GET_INTERPRETATION_INFO_ERROR: "GET_INTERPRETATION_INFO_ERROR",
};

export default GetInterpretationInfoType;